export const CATEGORIES = [
  { id: 'all', label: 'Բոլորը', emoji: '🍽️' },
  { id: 'starters', label: 'Նախուտեստ', emoji: '🥗' },
  { id: 'mains', label: 'Հիմնական', emoji: '🍖' },
  { id: 'pizza', label: 'Պիցցա', emoji: '🍕' },
  { id: 'burgers', label: 'Բուրգեր', emoji: '🍔' },
  { id: 'desserts', label: 'Անուշաբույր', emoji: '🍰' },
  { id: 'drinks', label: 'Ըմպելիք', emoji: '🥤' },
]

export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Կեսարի Աղցան',
    nameEn: 'Caesar Salad',
    category: 'starters',
    price: 2800,
    description: 'Թարմ ռոմեն սալաթ, կռեկեր, պարմեզան, կեսարի սոուս',
    calories: 320,
    prepTime: '10 ր',
    rating: 4.8,
    reviews: 124,
    tags: ['Վեգ', 'Հայտնի'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#4ade80',
  },
  {
    id: '2',
    name: 'Մսային Burg Classic',
    nameEn: 'Classic Burger',
    category: 'burgers',
    price: 4500,
    description: '200գ տավարի միս, չեդդեր, կաղամբ, լոլիկ, հատուկ սոուս',
    calories: 680,
    prepTime: '15 ր',
    rating: 4.9,
    reviews: 287,
    tags: ['Bestseller'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#f97316',
  },
  {
    id: '3',
    name: 'Մարգարիտ Պիցցա',
    nameEn: 'Margherita Pizza',
    category: 'pizza',
    price: 5200,
    description: '32սմ, մոցառելլա, թարմ բազիլ, լոլիկի սոուս',
    calories: 890,
    prepTime: '20 ր',
    rating: 4.7,
    reviews: 198,
    tags: ['Վեգ'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#ef4444',
  },
  {
    id: '4',
    name: 'Հրո Հավ',
    nameEn: 'Spicy Chicken',
    category: 'mains',
    price: 5800,
    description: 'Կծու մարինադով հավի ֆիլե, ձկնաբույն բրինձ, բանջարեղեն',
    calories: 720,
    prepTime: '25 ր',
    rating: 4.6,
    reviews: 156,
    tags: ['Կծու', 'Հայտնի'],
    spicy: true,
    available: true,
    model3d: null,
    color: '#f59e0b',
  },
  {
    id: '5',
    name: 'Շոկոլադե Ֆոնդան',
    nameEn: 'Chocolate Fondant',
    category: 'desserts',
    price: 2200,
    description: 'Տաք շոկոլադե կեքս հեղուկ կենտրոնով, վանիլի պաղպաղակ',
    calories: 480,
    prepTime: '12 ր',
    rating: 4.9,
    reviews: 312,
    tags: ['Bestseller'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#8b5cf6',
  },
  {
    id: '6',
    name: 'Թարմ Մրգային Ըմպելիք',
    nameEn: 'Fresh Fruit Juice',
    category: 'drinks',
    price: 1500,
    description: 'Թարմ մրգեր, ձմերուկ, ելակ, արհեստական ​​ներկ չկա',
    calories: 120,
    prepTime: '5 ր',
    rating: 4.7,
    reviews: 89,
    tags: ['Vegan', 'Թարմ'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#ec4899',
  },
  {
    id: '7',
    name: 'Ծովամթերք Ռիզոտտո',
    nameEn: 'Seafood Risotto',
    category: 'mains',
    price: 7200,
    description: 'Արբոռիո բրինձ, ծովախեցգետին, ականջ, մուսել, պարմեզան',
    calories: 640,
    prepTime: '30 ր',
    rating: 4.8,
    reviews: 143,
    tags: ['Chef\'s Choice'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#06b6d4',
  },
  {
    id: '8',
    name: 'Պեպերոնի Պիցցա',
    nameEn: 'Pepperoni Pizza',
    category: 'pizza',
    price: 5900,
    description: '32սմ, պեպերոնի, մոցառելլա, լոլիկի սոուս, ձիթաձեթ',
    calories: 960,
    prepTime: '20 ր',
    rating: 4.9,
    reviews: 421,
    tags: ['Bestseller'],
    spicy: true,
    available: true,
    model3d: null,
    color: '#dc2626',
  },
  {
    id: '9',
    name: 'Տիրամիսու',
    nameEn: 'Tiramisu',
    category: 'desserts',
    price: 2500,
    description: 'Դասական իտալական տիրամիսու, մասկարպոնե, կաֆե, կակաո',
    calories: 420,
    prepTime: '0 ր',
    rating: 4.8,
    reviews: 267,
    tags: ['Vegan friendly'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#a78bfa',
  },
  {
    id: '10',
    name: 'Գինով Ռեւ',
    nameEn: 'BBQ Ribs',
    category: 'mains',
    price: 8500,
    description: '400գ շոր կողիկ BBQ-ի սոուսով, կարտոֆիլ, կաղամբ',
    calories: 1100,
    prepTime: '35 ր',
    rating: 4.9,
    reviews: 178,
    tags: ['Chef\'s Choice', 'Հայտնի'],
    spicy: false,
    available: true,
    model3d: null,
    color: '#b45309',
  },
]

export const formatPrice = (price) =>
  new Intl.NumberFormat('hy-AM', {
    style: 'currency',
    currency: 'AMD',
    minimumFractionDigits: 0,
  }).format(price)
